pipeline {
  agent any

  tools {
    jdk 'Java 17'
    maven 'Maven'
  }

  stages {

    stage('Checkout Code') {
      steps {
        echo 'Pulling from Github'
        git branch: 'main',
            credentialsId: 'git_cred',
            url: 'https://github.com/Jayanth-N-Murthy/wipjen.git'
      }
    }

    stage('Test Code') {
      steps {
        echo 'JUNIT Test case execution started'
        bat 'mvn clean test'
      }
      post {
        always {
          junit '**/target/surefire-reports/*.xml'
          echo 'Test Run is SUCCESSFUL!'
        }
      }
    }

    stage('Build Project') {
      steps {
        echo 'Building Java project'
        bat 'mvn clean package -DskipTests'
      }
    }

    stage('Build the Docker Image') {
      steps {
        echo 'Building Docker Image'
        bat 'docker build -t jayanthn1/indiaproj:1.0 .'
      }
    }

    stage('Push Docker Image to DockerHub') {
      steps {
        echo 'Pushing Docker Image'
        withCredentials([usernamePassword(
          credentialsId: 'Docker_id',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          bat '''
            echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
            docker push jayanthn1/indiaproj:1.0
          '''
        }
      }
    }

    stage('Deploy Project to K8s') {
      steps {
        echo 'Deploy Java project to Kubernetes'
        bat '''
          minikube delete
          minikube start
          minikube image load jayanthn1/indiaproj:1.0

          kubectl apply -f k8/deployment.yaml
          kubectl apply -f k8/services.yaml

          kubectl get pods
          kubectl describe pods
          kubectl get services

          minikube addons enable dashboard
          minikube dashboard
        '''
      }
    }

  }

  post {
    success {
      echo 'Build and Run is SUCCESSFUL!'
    }
    failure {
      echo 'OOPS!!! Failure.'
    }
  }
}
