pipeline {
  agent any

  tools {
    jdk 'Java 17'
    maven 'Maven'
  }

  stages {

    stage('Checkout Code') {
      steps {
        echo 'Pulling from Github'
        git branch: 'main',
            credentialsId: 'git_cred',
            url: 'https://github.com/Jayanth-N-Murthy/wipjen.git'
      }
    }

    stage('Test Code') {
      steps {
        echo 'JUNIT Test case execution started'
        dir('indiaproj') {
          bat 'mvn clean test'
        }
      }
      post {
        always {
          junit allowEmptyResults: true,
                testResults: '**/target/surefire-reports/*.xml'
          echo 'Test stage completed'
        }
      }
    }

    stage('Build Project') {
      steps {
        echo 'Building Java project'
        dir('indiaproj') {
          bat 'mvn clean package -DskipTests'
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('indiaproj') {
          echo 'Building Docker Image'
          bat 'docker build -t jayanthn1/indiaproj:1.0 .'
        }
      }
    }

    stage('Push Docker Image to DockerHub') {
      steps {
        echo 'Pushing Docker Image'
        withCredentials([usernamePassword(
          credentialsId: 'Docker_id',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          bat '''
            echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
            docker push jayanthn1/indiaproj:1.0
          '''
        }
      }
    }

    stage('Deploy Project to K8s') {
      steps {
        echo 'Deploy Java project to Kubernetes'
        dir('indiaproj') {
          bat '''
            minikube delete
            minikube start
            minikube image load jayanthn1/indiaproj:1.0

            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/services.yaml

            kubectl get pods
            kubectl get services
          '''
        }
      }
    }
  }

  post {
    success {
      echo 'Build and Deployment SUCCESSFUL!'
    }
    failure {
      echo 'OOPS!!! Failure.'
    }
  }
}
